tucargaapi/apps/profiles/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (CompanyProfileUpdateView,
                    TransportCompanyProfileView,
                    TransportCompanyProfileUpdateView)

urlpatterns = patterns(
    '',
    url(r'^transportcompany/$',
        login_required(TransportCompanyProfileView.as_view()),
        name='profile-transportcompany'),
    url(r'^company/(?P<pk>\d+)/$',
        login_required(CompanyProfileUpdateView.as_view()),
        name='profile-company-update'),
    url(r'^transportcompany/(?P<pk>\d+)/$',
        login_required(TransportCompanyProfileUpdateView.as_view()),
        name='profile-transportcompany-update'),

)

tucargaapi/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.conf import settings

# See: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#hooking-adminsite-instances-into-your-urlconf
admin.autodiscover()

# See: https://docs.djangoproject.com/en/dev/topics/http/urls/
urlpatterns = patterns(
    '',
    # Django NoPassWord
    url(r'^accounts/login-code/(?P<login_code>[a-zA-Z0-9]+)/$',
        'django_nopassword.views.login_with_code',
        name='login-with-code'),
    url(r'^accounts/logout/$',
        'django_nopassword.views.logout',
        name='logout',
        kwargs={
            'redirect_to': settings.SUCCESS_URL.url}),

    # Local apps
    url(r'^directory/', include('tucargaapi.apps.directory.urls')),
    url(r'^rates/', include('tucargaapi.apps.rates.urls')),
    url(r'^profiles/', include('tucargaapi.apps.profiles.urls')),

    # Admin panel and documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/salmonella/', include('salmonella.urls')),
)

tucargaapi/apps/profiles/models.py
from django.db import models

# Create your models here.

tucargaapi/apps/rates/models.py
# encoding: utf-8

from django.core.urlresolvers import reverse
from django.db import models

from model_utils.models import TimeStampedModel

from tucargaapi.apps.routes.models import RouteImport, RouteExport


class RateAbstractBase(TimeStampedModel):

    VALIDITY_30 = 30
    VALIDITY_60 = 60
    VALIDITY_90 = 90

    VALIDITY_CHOICES = (
        (VALIDITY_30, '30 días'),
        (VALIDITY_60, '60 días'),
        (VALIDITY_90, '90 días'),
        )

    validity = models.IntegerField('Vigencia', choices=VALIDITY_CHOICES,
                                   default=VALIDITY_90)
    transportcompany = models.ForeignKey('directory.TransportCompany')

    class Meta:
        abstract = True


class RateImport(RateAbstractBase):

    oneway = models.IntegerField('$ Oneway', null=True, blank=True)
    roundtrip = models.IntegerField('$ Roundtrip', null=True, blank=True)
    route = models.ForeignKey(RouteImport)

    class Meta:
        verbose_name = 'tarifa importación'
        verbose_name_plural = 'tarifas importación'

    def get_update_url(self):
        return reverse('rate-import-update', args=[str(self.id)])


class RateExport(RateAbstractBase):

    amount = models.IntegerField('precio + IVA')
    route = models.ForeignKey(RouteExport)

    class Meta:
        verbose_name = 'tarifa exportación'
        verbose_name_plural = 'tarifas exportación'

    def get_update_url(self):
        return reverse('rate-export-update', args=[str(self.id)])

tucargaapi/apps/profiles/forms.py
# encoding: utf-8

from django import forms

from tucargaapi.apps.directory.models import (Company, Coverage, TransportCompany,
                                              FreightDetail)


class CompanyProfileForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('logo', 'name', 'business_name', 'year_of_creation', 'phone')


class TransportCompanyProfileForm(forms.ModelForm):

    coverage = forms.ModelMultipleChoiceField(
        label='Cobertura',
        widget=forms.CheckboxSelectMultiple,
        queryset=Coverage.objects.all(),
        required=False)

    freight_types = forms.MultipleChoiceField(
        label='Tipos de carga',
        widget=forms.CheckboxSelectMultiple,
        choices=FreightDetail.OBJ_TYPES,
        required=False)

    class Meta:
        model = TransportCompany
        fields = ('number_of_trips_per_month', 'coverage', 'freight_types')

    def clean_freight_types(self):
        field = []
        for data in self.cleaned_data['freight_types']:
            field.append(str(data))
        field = ','.join([f for f in field])
        return field

tucargaapi/apps/profiles/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from tucargaapi.apps.directory.models import Company, TransportCompany

from .forms import CompanyProfileForm, TransportCompanyProfileForm
import utils


class TransportCompanyProfileView(TemplateView):

    template_name = 'profile_transportcompany.html'

    def get_context_data(self, **kwargs):
        context = super(TransportCompanyProfileView,
                        self).get_context_data(**kwargs)
        company = self.request.user.userdirectory.company
        transportcompany = company.transportcompany
        context['transportcompany'] = transportcompany

        # get company profile form
        companyprofile_form = CompanyProfileForm(instance=company)
        context['companyprofile_form'] = companyprofile_form

        # get transportcompany profile form
        transportcompanyprofile_form = TransportCompanyProfileForm(
            instance=transportcompany)
        context['transportcompanyprofile_form'] = transportcompanyprofile_form

        # get export forms
        exportroute_forms, has_rateexport = utils.get_exportrates_forms(
            transportcompany)
        context['exportroute_forms'] = exportroute_forms
        context['has_rateexport'] = has_rateexport

        # get import forms
        importroute_forms, has_rateimport = utils.get_importrates_forms(
            transportcompany)

        context['importroute_forms'] = importroute_forms
        context['has_rateimport'] = has_rateimport

        return context


class CompanyProfileUpdateView(UpdateView):

    template_name = 'profile_company_update.html'
    model = Company
    form_class = CompanyProfileForm
    success_url = reverse_lazy('profile-transportcompany')


class TransportCompanyProfileUpdateView(UpdateView):

    template_name = 'profile_transportcompany_update.html'
    model = TransportCompany
    form_class = TransportCompanyProfileForm
    success_url = reverse_lazy('profile-transportcompany')

tucargaapi/apps/profiles/templates/profile_company_update.html
{% extends "base.html" %}

{% block content %}

{{ form }}

{% endblock %}

tucargaapi/apps/profiles/templates/profile_transportcompany.html
{% extends "base.html" %}

{% block content %}
<div id="content-page">
    <div  class="row">

    <div id="sidebar" class="large-3 medium-4 columns">
        <div class="nav-view">
            <ul class="tabs" data-tab>
                <li><a href="#panel2-1" class="">Rutas frecuentes</a></li>
                <li><a href="#panel2-3">Datos empresa</a></li>
                <li><a href="#panel2-2">Datos contacto</a></li>
            </ul>
        </div>

        <div class="box contact">
            <div class="margin">
                <a href="#/contacto">Te ayudamos</a>
                <p>En <b>Tucarga</b> siempre estamos dispuesto a ayudarte, habla con nosotros al 600 500 0606</p>
            </div>
        </div>
    </div>

    <div id="content-view" class="large-9 medium-8 columns">
        <div class="box columns">

        <div class="tabs-content">
          <div class="content active" id="panel2-1">
            {% include "profiles/rate.html" %}
          </div>
          <div class="content" id="panel2-2">
            {% include "profiles/companyprofile.html" %}
          </div>
          <div class="content" id="panel2-3">
            {% include "profiles/transportcompanyprofile.html" %}
          </div>
        </div>

        </div>
    </div>
</div>

<script>
  var is_input_valid = function(tablerow) {
    if(tablerow.hasClass("export")) {
      var amount = tablerow.find('#id_amount')
      if(!amount.val()) {
        return false
      }
    }
    if(tablerow.hasClass("import")) {
      var oneway = tablerow.find('#id_oneway')
      var roundtrip = tablerow.find('#id_roundtrip')
      if(!(oneway.val() || roundtrip.val())) {
        return false
      }
    }
    return true
  }

  var update_form = function(form, msg) {
    var patch_input = form.find('.patch')
    if(patch_input.length == 0) {
      // Actualizar form.action
      form.attr('action', msg.update_url)
      var input = $('<input>').attr({
        id: 'patch',
        class: 'patch',
        type: 'hidden',
        value: 'PATCH',
        name: '_method',
      })
      form.append(input)
    }
  }

  var update_rate_handler = function() {
    var tablerow = $(this).parent().parent()
    var route = $(tablerow).attr('route')
    var form = tablerow.find('#form-' + route)

    if(!is_input_valid(tablerow)) {
      return
    }

    if(tablerow.hasClass("creating")) {
      return
    }

    var url = form.attr('action')
    var payload = form.serialize()

    tablerow.addClass("creating")
    $.ajax({
      type: "POST",
      url: url,
      data: payload
    })
      .done(function(msg) {
        // Elimino el div de alert
        $('.alert-box ').hide()
        // Actualizar boton
        var button = tablerow.find('.status')
        button.addClass('check')
        tablerow.removeClass("creating")
        update_form(form, msg)
      });
  }

  // bind handler for export validity fields
  $(function() {
    $('.export-rate').each(function(index) {
      $(this).find('#id_validity').blur(update_rate_handler);
    });
  });
  // bind handler for export amount fields
  $(function() {
    $('.export-rate').each(function(index) {
      $(this).find('#id_amount').blur(update_rate_handler);
    });
  });

  // bind handler for import validity fields
  $(function() {
    $('.import-rate').each(function(index) {
      $(this).find('#id_validity').blur(update_rate_handler);
    });
  });
  // bind handler for import oneway fields
  $(function() {
    $('.import-rate').each(function(index) {
      $(this).find('#id_oneway').blur(update_rate_handler);
    });
  });
  // bind handler for import roundtrip fields
  $(function() {
    $('.import-rate').each(function(index) {
      $(this).find('#id_roundtrip').blur(update_rate_handler);
    });
  });

  // // Tabs for the ruotes
  $('ul.tabs').each(function(){
    // For each set of tabs, we want to keep track of
    // which tab is active and it's associated content
    var $active, $content, $links = $(this).find('a');

    // If the location.hash matches one of the links, use that as the active tab.
    // If no match is found, use the first link as the initial active tab.
    $active = $($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
    $active.addClass('active');

    $content = $($active[0].hash);

    // Hide the remaining content
    $links.not($active).each(function () {
      $(this.hash).hide();
    });

    // Bind the click event handler
    $(this).on('click', 'a', function(e){
      // Make the old tab inactive.
      $active.removeClass('active');
      $content.hide();

      // Update the variables with the new link and content
      $active = $(this);
      $content = $(this.hash);

      // Make the tab active.
      $active.addClass('active');
      $content.show();

      // Prevent the anchor's default click action
      e.preventDefault();
    });
  });

  $( "label:contains(':')" ).addClass('headLabel')

  </script>

{% endblock %}

tucargaapi/apps/profiles/templates/profile_transportcompany_update.html
{% extends "base.html" %}

{% block content %}

  <h1>Perfil empresa transporte</h1>

  <form method="POST" action="{% url 'profile-transportcompany-update' pk=transportcompany.pk %}">

    {% csrf_token %}
    
    {{ form }}

    <button class="button success radius large-12">Actualizar</button>
  </form>

{% endblock %}